import BarChart from '../components/BarChart'
import MetricCard from '../components/MetricCard'
import ContextStrip from '../components/ContextStrip'
import type { Alpha810FactorEvidence, Alpha810Snapshot } from '../types'
import { useLocale } from '../i18n'

function metric(value: number | null, english = false, digits = 4) {
  return value === null || !Number.isFinite(value) ? english ? 'No data' : '暂无数据' : value.toFixed(digits)
}

export default function Alpha810FactorPage({ factor, snapshot }: { factor?: Alpha810FactorEvidence; snapshot: Alpha810Snapshot }) {
  const { locale, copy } = useLocale()
  const english = locale === 'en-US'
  if (!factor) return <main className="empty"><h1>{english ? 'Alpha factor not found' : '未找到 Alpha 因子'}</h1><p>{english ? 'This factor is not in the current public snapshot.' : '这个因子不在当前公开快照中。'}</p><a href={`${import.meta.env.BASE_URL}alpha810`}>{english ? 'Back to Alpha 810' : '返回 Alpha 810'}</a></main>
  const groupLabels = factor.group_returns.map((item) => `G${item.group}`)
  const groupValues = factor.group_returns.map((item) => item.mean_return)
  const firstGroupReturn = factor.group_returns[0]?.mean_return
  const lastGroupReturn = factor.group_returns[factor.group_returns.length - 1]?.mean_return
  const topBottomSpread = firstGroupReturn !== null && firstGroupReturn !== undefined && lastGroupReturn !== null && lastGroupReturn !== undefined ? lastGroupReturn - firstGroupReturn : null
  return <main className="page factor-detail-page">
    <a className="back" href={`${import.meta.env.BASE_URL}alpha810`}>← {english ? 'Alpha 810 factor catalog' : 'Alpha 810 因子目录'}</a>
    <section className="detail-head"><p className="eyebrow">{factor.family} / PUBLIC EVIDENCE</p><h1>{factor.name}</h1><p className="lede">{english ? 'Aggregate cross-sectional diagnostics from the current public snapshot.' : '当前公开快照中的横截面聚合诊断。'}</p></section>
    <ContextStrip items={[{ label: english ? 'Data version' : '数据版本', value: snapshot.data_version }, { label: english ? 'Observation range' : '观测区间', value: `${snapshot.dataset.date_start ?? '—'} → ${snapshot.dataset.date_end ?? '—'}` }, { label: english ? 'Coverage' : '覆盖率', value: factor.coverage.ratio === null ? '—' : `${(factor.coverage.ratio * 100).toFixed(1)}%` }, { label: english ? 'Return field' : '收益字段', value: snapshot.dataset.return_column }]} />
    <div className="metrics"><MetricCard label={english ? 'Mean IC' : 'IC 均值'} value={metric(factor.ic.mean, english)} note={`IR ${metric(factor.ic.ir, english, 3)}`} /><MetricCard label={english ? 'Mean RankIC' : 'RankIC 均值'} value={metric(factor.rank_ic.mean, english)} note={`IR ${metric(factor.rank_ic.ir, english, 3)}`} /><MetricCard label={english ? 'Positive IC rate' : 'IC 正值比例'} value={factor.ic.positive_rate === null ? english ? 'No data' : '暂无数据' : `${(factor.ic.positive_rate * 100).toFixed(1)}%`} /><MetricCard label={english ? 'Positive RankIC rate' : 'RankIC 正值比例'} value={factor.rank_ic.positive_rate === null ? english ? 'No data' : '暂无数据' : `${(factor.rank_ic.positive_rate * 100).toFixed(1)}%`} /></div>
    <section className="evidence-card-row"><article><span>{copy.alpha810.directionConsistency}</span><strong>{factor.rank_ic.positive_rate === null ? '—' : `${(factor.rank_ic.positive_rate * 100).toFixed(1)}%`}</strong><small>{copy.alpha810.stabilityNote}</small></article><article><span>{copy.alpha810.groupSpread}</span><strong>{metric(topBottomSpread, english, 4)}</strong><small>{copy.alpha810.spreadNote}</small></article><article><span>{copy.alpha810.snapshotInterval}</span><strong>{snapshot.dataset.date_start ?? '—'} → {snapshot.dataset.date_end ?? '—'}</strong><small>{copy.alpha810.fullWindow}</small></article></section>
    <div className="detail-grid"><section className="panel"><p className="eyebrow">COVERAGE</p><h2>{english ? 'Data coverage' : '数据覆盖'}</h2><dl className="research-dl"><div><dt>{english ? 'Valid observations' : '有效观测'}</dt><dd>{factor.coverage.valid_observations.toLocaleString()}</dd></div><div><dt>{english ? 'Total observations' : '总观测'}</dt><dd>{factor.coverage.total_observations.toLocaleString()}</dd></div><div><dt>{english ? 'Return field' : '收益字段'}</dt><dd>{snapshot.dataset.return_column}</dd></div></dl></section><section className="panel"><p className="eyebrow">GROUP RETURNS</p><h2>{english ? 'Average return by factor group' : '因子分组平均收益'}</h2>{factor.group_returns.length ? <BarChart labels={groupLabels} values={groupValues} colors={groupLabels.map((_, index) => index === groupLabels.length - 1 ? '#b64d33' : '#d8a58b')} percent /> : <div className="chart-empty">{english ? 'No grouped returns in this snapshot.' : '当前快照没有分组收益。'}</div>}<p className="panel-note">{english ? 'G1 contains the lowest factor values; G5 the highest. Each bar averages daily cross-sectional mean returns across available dates. Percent per return observation; no compounding or trading costs.' : 'G1 为最低因子值组，G5 为最高组。每根柱先按日计算组内横截面平均收益，再跨可用日期平均；单位为每次收益观测的百分比，未复利、未扣交易成本。'}</p></section></div>
    <section className="panel methodology-panel"><p className="eyebrow">HOW TO READ THE METRICS</p><h2>{english ? 'Method and limits' : '指标口径与边界'}</h2><p>{english ? 'IC is the daily cross-sectional Pearson correlation; RankIC is Spearman correlation. IR divides the mean daily correlation by its population standard deviation. Positive rate is the share of valid dates with a positive correlation.' : 'IC 是逐日横截面 Pearson 相关系数，RankIC 是 Spearman 相关系数。IR 为逐日相关系数均值除以总体标准差；正值比例是有效日期中相关系数大于零的占比。'}</p><p>{english ? 'The snapshot identifies its target only as next_period_return. Its exact holding interval and execution timing are not specified in this public contract; inspect the upstream data definition before drawing trading conclusions.' : '公开契约仅将目标字段标为 next_period_return，未说明精确持有时长与执行时点；作交易解释前需核对上游数据定义。'}</p><p>{english ? 'Group period counts can differ by factor and group; these values are descriptive aggregate evidence, not a strategy backtest.' : '分组有效期数可能因因子和组别而异；这里是描述性聚合证据，不是策略回测。'}</p></section>
    <section className="research-boundary"><p><strong>{english ? 'Evidence boundary: ' : '研究边界：'}</strong>{snapshot.public_limits.join(' ')}</p></section>
  </main>
}
