import BarChart from '../components/BarChart'
import MetricCard from '../components/MetricCard'
import type { Alpha810FactorEvidence, Alpha810Snapshot } from '../types'
import { useLocale } from '../i18n'

function metric(value: number | null, english = false) {
  return value === null || !Number.isFinite(value) ? english ? 'No data' : '暂无数据' : value.toFixed(3)
}

export default function Alpha810FactorPage({ factor, snapshot }: { factor?: Alpha810FactorEvidence; snapshot: Alpha810Snapshot }) {
  const { locale } = useLocale()
  const english = locale === 'en-US'
  if (!factor) return <main className="empty"><h1>{english ? 'Alpha factor not found' : '未找到 Alpha 因子'}</h1><p>{english ? 'This factor is not in the current public snapshot.' : '这个因子不在当前公开快照中。'}</p><a href={`${import.meta.env.BASE_URL}alpha810`}>{english ? 'Back to Alpha 810' : '返回 Alpha 810'}</a></main>
  const groupLabels = factor.group_returns.map((item) => `G${item.group}`)
  const groupValues = factor.group_returns.map((item) => item.mean_return)
  return <main className="page factor-detail-page"><a className="back" href={`${import.meta.env.BASE_URL}alpha810`}>← {english ? 'Alpha 810 factor catalog' : 'Alpha 810 因子目录'}</a><section className="detail-head"><p className="eyebrow">{factor.family} / PUBLIC EVIDENCE</p><h1>{factor.name}</h1><p className="lede">{english ? 'This is aggregate factor evidence from the current public snapshot. Exact operators, per-security values, and portfolio weights are not shown.' : '这是当前公开快照中的聚合因子证据。页面不展示精确算子、逐股票值或组合权重。'}</p><div className="detail-tags"><span className="tag">{snapshot.data_version}</span><span className="tag">{snapshot.dataset.date_start ?? '—'} → {snapshot.dataset.date_end ?? '—'}</span><span className="tag">{factor.coverage.ratio === null ? english ? 'Coverage unavailable' : '覆盖率暂无数据' : `${english ? 'Coverage' : '覆盖率'} ${(factor.coverage.ratio * 100).toFixed(1)}%`}</span></div></section><div className="metrics"><MetricCard label={english ? 'Mean IC' : 'IC 均值'} value={metric(factor.ic.mean, english)} note={`IR ${metric(factor.ic.ir, english)}`} /><MetricCard label={english ? 'Mean RankIC' : 'RankIC 均值'} value={metric(factor.rank_ic.mean, english)} note={`IR ${metric(factor.rank_ic.ir, english)}`} /><MetricCard label={english ? 'Positive IC rate' : 'IC 正值比例'} value={factor.ic.positive_rate === null ? english ? 'No data' : '暂无数据' : `${(factor.ic.positive_rate * 100).toFixed(1)}%`} /><MetricCard label={english ? 'Positive RankIC rate' : 'RankIC 正值比例'} value={factor.rank_ic.positive_rate === null ? english ? 'No data' : '暂无数据' : `${(factor.rank_ic.positive_rate * 100).toFixed(1)}%`} /></div><div className="detail-grid"><section className="panel"><p className="eyebrow">COVERAGE</p><h2>{english ? 'Data coverage' : '数据覆盖'}</h2><dl className="research-dl"><div><dt>{english ? 'Valid observations' : '有效观测'}</dt><dd>{factor.coverage.valid_observations.toLocaleString()}</dd></div><div><dt>{english ? 'Total observations' : '总观测'}</dt><dd>{factor.coverage.total_observations.toLocaleString()}</dd></div><div><dt>{english ? 'Return basis' : '研究口径'}</dt><dd>{snapshot.dataset.return_column}</dd></div></dl></section><section className="panel"><p className="eyebrow">GROUP RETURNS</p><h2>{english ? 'Grouped returns' : '分组收益'}</h2>{factor.group_returns.length ? <BarChart labels={groupLabels} values={groupValues} colors={groupLabels.map((_, index) => index === groupLabels.length - 1 ? '#b64d33' : '#d8a58b')} /> : <div className="chart-empty">{english ? 'The current snapshot has no grouped returns to display.' : '当前快照没有可展示的分组收益。'}</div>}<p className="panel-note">{english ? 'Each group is an aggregate cross-sectional average return; it is not a complete strategy backtest.' : '每组是横截面排序后的聚合平均收益；它不是完整策略回测结果。'}</p></section></div><section className="research-boundary"><p><strong>{english ? 'Evidence boundary:' : '研究边界：'}</strong>{snapshot.public_limits.join(' ')}</p></section></main>
}
