import { lazy } from 'react'
import { useMemo, useState } from 'react'
import MetricCard from '../components/MetricCard'
import ContextStrip from '../components/ContextStrip'
import DeferredContent from '../components/DeferredContent'
import type { Alpha810FactorEvidence, Alpha810Snapshot } from '../types'
import { useLocale } from '../i18n'

const ResearchCharts = lazy(() => import('../components/ResearchCharts'))

function metric(value: number | null, english = false) {
  return value === null || !Number.isFinite(value) ? english ? 'No data' : '暂无数据' : value.toFixed(4)
}

function factorScore(factor: Alpha810FactorEvidence) {
  return factor.rank_ic.mean ?? Number.NEGATIVE_INFINITY
}

export default function Alpha810OverviewPage({ snapshot }: { snapshot: Alpha810Snapshot }) {
  const { locale, copy } = useLocale()
  const english = locale === 'en-US'
  const [query, setQuery] = useState('')
  const [family, setFamily] = useState('all')
  const families = [...new Set(snapshot.factors.map((factor) => factor.family))].sort()
  const factors = useMemo(() => snapshot.factors
    .filter((factor) => family === 'all' || factor.family === family)
    .filter((factor) => `${factor.name} ${factor.family}`.toLowerCase().includes(query.toLowerCase().trim()))
    .sort((left, right) => factorScore(right) - factorScore(left)), [family, query, snapshot.factors])
  const byQValues = Object.values(snapshot.multiple_testing?.factors ?? {})
    .map((item) => item.q_value_by)
    .filter((value): value is number => typeof value === 'number' && Number.isFinite(value))
  const byBelowThreshold = byQValues.filter((value) => value <= 0.05).length
  const hasMultipleTesting = Boolean(
    snapshot.multiple_testing && snapshot.multiple_testing.status !== 'not_provided',
  )

  return <main className="page">
    <section className="hero"><p className="eyebrow">ALPHA 810 / PUBLIC EVIDENCE</p><h1>{english ? <>Classic factors, <em>evidence first.</em></> : <>经典因子，<em>先看证据。</em></>}</h1><p className="lede">{english ? 'Browse aggregate research evidence for Alpha101, Alpha191, Alpha158, and Alpha360. These are auditable descriptive statistics, not investment advice.' : '浏览 Alpha101、Alpha191、Alpha158 和 Alpha360 的聚合研究证据。这里展示的是可审计的描述性统计，不是交易建议。'}</p><span className="badge">AGGREGATE SNAPSHOT</span></section>
    <ContextStrip items={[{ label: english ? 'Data version' : '数据版本', value: snapshot.data_version }, { label: english ? 'Observation range' : '观测区间', value: `${snapshot.dataset.date_start ?? '—'} → ${snapshot.dataset.date_end ?? '—'}` }, { label: english ? 'Snapshot generated' : '快照生成', value: `${snapshot.generated_at.slice(0, 16).replace('T', ' ')} UTC` }, { label: english ? 'Return field' : '收益字段', value: snapshot.dataset.return_column }]} />
    <section className="metrics"><MetricCard label={english ? 'Factors' : '因子'} value={snapshot.factors.length.toLocaleString()} note={english ? 'Current public snapshot' : '当前公开快照'} /><MetricCard label={english ? 'Families' : '因子族'} value={families.length.toLocaleString()} note={families.join(' · ')} /><MetricCard label={english ? 'Trading days' : '交易日'} value={snapshot.dataset.trading_days.toLocaleString()} note={`${snapshot.dataset.ticker_count.toLocaleString()} ${english ? 'covered names' : '个覆盖标的'}`} /><MetricCard label={english ? 'Quality gate' : '质量门禁'} value={snapshot.quality.status.toUpperCase()} tone={snapshot.quality.status} note={`${snapshot.quality.summary.low_coverage_factor_count} ${english ? 'low-coverage factors' : '个低覆盖因子'}`} /></section>
    <section className="panel"><div className="panel-head"><p className="eyebrow">SIGNAL QUALITY</p><h2>{english ? 'Signal checks' : '信号检查'}</h2></div><p>{english ? 'The quality gate warns when any factor has under 80% coverage or is missing a RankIC mean. It does not measure strategy performance.' : '质量门禁在因子覆盖率低于 80% 或缺少 RankIC 均值时告警；它不衡量策略收益。'}</p><div className="quality-summary"><span>{snapshot.quality.summary.low_coverage_factor_count} {english ? 'factors below 80% coverage' : '个因子覆盖率低于 80%'}</span><span>{snapshot.quality.summary.missing_rank_ic_factor_count} {english ? 'without RankIC mean' : '个因子缺少 RankIC 均值'}</span></div><div className="evidence-metrics"><div><span>{english ? 'Mean coverage' : '平均覆盖率'}</span><strong>{snapshot.quality.summary.coverage_mean === null ? '—' : `${(snapshot.quality.summary.coverage_mean * 100).toFixed(1)}%`}</strong></div><div><span>{english ? 'Minimum coverage' : '最低覆盖率'}</span><strong>{snapshot.quality.summary.coverage_min === null ? '—' : `${(snapshot.quality.summary.coverage_min * 100).toFixed(1)}%`}</strong></div><div><span>{english ? 'Mean RankIC across factors' : '因子 RankIC 均值的平均'}</span><strong>{metric(snapshot.quality.summary.rank_ic_mean, english)}</strong></div><div><span>{english ? 'Mean positive RankIC rate' : '因子 RankIC 正值率的平均'}</span><strong>{snapshot.quality.summary.rank_ic_positive_rate_mean === null ? '—' : `${(snapshot.quality.summary.rank_ic_positive_rate_mean * 100).toFixed(1)}%`}</strong></div></div><p className="panel-note">{english ? 'Quality source snapshot' : '质量报告引用的源快照'}: {snapshot.quality.source.generated_at.slice(0, 16).replace('T', ' ')} UTC</p></section>
    <section className="panel"><div className="panel-head"><p className="eyebrow">{copy.alpha810.overviewTesting}</p><h2>{copy.alpha810.overviewTestingTitle}</h2></div><div className="evidence-metrics"><div><span>{copy.alpha810.byBelowThreshold}</span><strong>{hasMultipleTesting ? byBelowThreshold.toLocaleString() + ' / ' + (snapshot.multiple_testing?.family_size ?? '—') : '—'}</strong></div><div><span>{copy.alpha810.testsAvailable}</span><strong>{hasMultipleTesting ? (snapshot.multiple_testing?.tested_count ?? '—').toLocaleString() + ' / ' + (snapshot.multiple_testing?.family_size ?? snapshot.factors.length).toLocaleString() : '—'}</strong></div><div><span>{copy.alpha810.regimeAvailability}</span><strong>{snapshot.temporal_validation?.market_regime?.status === 'complete' ? copy.alpha810.available : copy.alpha810.unavailable}</strong></div></div><p className="panel-note">{hasMultipleTesting ? copy.alpha810.overviewTestingNote : copy.alpha810.overviewTestingUnavailable}</p>{snapshot.temporal_validation?.market_regime?.status === 'not_provided' ? <p className="panel-note">{copy.alpha810.regimeUnavailable}</p> : null}</section>
    <section className="section"><div className="section-heading"><p className="eyebrow">DISTRIBUTION / 810 FACTORS</p><h2>{english ? 'See the whole distribution' : '看完整体分布'}</h2><p className="section-description">{english ? `Aggregate diagnostics for ${snapshot.dataset.date_start ?? 'the current'} to ${snapshot.dataset.date_end ?? 'the current'}; averages alone hide low-coverage and missing factors.` : `${snapshot.dataset.date_start ?? '当前'} 至 ${snapshot.dataset.date_end ?? '当前'} 的聚合诊断；只看均值会掩盖低覆盖和缺失因子。`}</p></div><div className="chart-grid"><section className="panel"><h3>{english ? 'Coverage by factor' : '因子覆盖率分布'}</h3><DeferredContent minHeight={300} label={english ? 'Loading chart…' : '图表加载中…'}><ResearchCharts kind="coverage" factors={snapshot.factors} english={english} /></DeferredContent><p className="panel-note">{english ? 'Bars count factors; the 80% threshold is the quality gate.' : '柱高为因子数量；80% 是质量门禁阈值。'}</p></section><section className="panel"><h3>{english ? 'Mean RankIC distribution' : 'RankIC 均值分布'}</h3><DeferredContent minHeight={300} label={english ? 'Loading chart…' : '图表加载中…'}><ResearchCharts kind="rankic" factors={snapshot.factors} english={english} /></DeferredContent><p className="panel-note">{english ? `${snapshot.quality.summary.missing_rank_ic_factor_count} factors with missing RankIC are omitted.` : `缺少 RankIC 的 ${snapshot.quality.summary.missing_rank_ic_factor_count} 个因子未纳入。`}</p></section></div><section className="panel scatter-panel"><h3>{english ? 'Coverage and mean RankIC' : '覆盖率与 RankIC 均值'}</h3><DeferredContent minHeight={300} label={english ? 'Loading chart…' : '图表加载中…'}><ResearchCharts kind="scatter" factors={snapshot.factors} english={english} /></DeferredContent><p className="panel-note">{english ? 'Each dot is one factor. Correlation here is descriptive, not evidence of predictive robustness.' : '每个点代表一个因子；图中的关系仅作描述，不代表预测稳健性。'}</p></section><section className="panel stability-panel"><div className="section-heading"><p className="eyebrow">{copy.alpha810.stability}</p><h3>{copy.alpha810.stabilityTitle}</h3><p className="panel-note">{copy.alpha810.stabilityNote}</p></div><DeferredContent minHeight={300} label={english ? 'Loading chart…' : '图表加载中…'}><ResearchCharts kind="rankic-positive-rate" factors={snapshot.factors} english={english} /></DeferredContent><div className="stability-summary"><span>{copy.alpha810.meanPositive}</span><strong>{snapshot.quality.summary.rank_ic_positive_rate_mean === null ? '—' : `${(snapshot.quality.summary.rank_ic_positive_rate_mean * 100).toFixed(1)}%`}</strong></div></section></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">FACTOR CATALOG</p><div className="section-heading-row"><h2>{english ? 'Alpha factor catalog' : 'Alpha 因子目录'}</h2><span className="muted">{english ? 'Sorted by mean RankIC' : '按 RankIC 均值排序'}</span></div></div><div className="explorer-toolbar"><label className="search-field">{english ? 'Search' : '搜索'}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="alpha101_001" /></label><label>{english ? 'Family' : '因子族'}<select value={family} onChange={(event) => setFamily(event.target.value)}><option value="all">{english ? 'All' : '全部'}</option>{families.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><div className="explorer-summary"><strong>{factors.length}</strong><span>{english ? 'matching factors' : '个匹配因子'}</span></div><div className="table-scroll"><table className="factor-table"><thead><tr><th>{english ? 'Factor' : '因子'}</th><th>{english ? 'Coverage' : '覆盖率'}</th><th>IC</th><th>RankIC</th><th>{english ? 'Grouped returns' : '分组收益'}</th></tr></thead><tbody>{factors.map((factor) => <tr key={factor.name}><td><a href={`${import.meta.env.BASE_URL}alpha810/factors/${encodeURIComponent(factor.name)}`}><strong>{factor.name}</strong><small>{factor.family}</small></a></td><td>{factor.coverage.ratio === null ? english ? 'No data' : '暂无数据' : `${(factor.coverage.ratio * 100).toFixed(1)}%`}</td><td>{metric(factor.ic.mean, english)}</td><td>{metric(factor.rank_ic.mean, english)}</td><td>{factor.group_returns.length ? `${factor.group_returns.length} ${english ? 'groups' : '组'}` : english ? 'No data' : '暂无数据'}</td></tr>)}</tbody></table>{!factors.length ? <div className="empty-filter"><h2>{english ? 'No matching factors' : '没有匹配结果'}</h2><p>{english ? 'Adjust the search term or factor family.' : '请调整搜索词或因子族。'}</p></div> : null}</div></section>
    <section className="research-boundary"><p><strong>{english ? 'Public boundary: ' : '公开边界：'}</strong>{snapshot.public_limits.join(' ')}</p></section>
  </main>
}
