import MetricCard from '../components/MetricCard'
import ContextStrip from '../components/ContextStrip'
import ResearchCharts from '../components/ResearchCharts'
import type { FactorRecord, FundamentalSnapshot, ResearchContext, Snapshot } from '../types'
import { useLocale } from '../i18n'

export default function OverviewPage({ snapshot, records, context, fundamental }: { snapshot: Snapshot; records: FactorRecord[]; context: ResearchContext; fundamental: FundamentalSnapshot }) {
  const { locale } = useLocale()
  const english = locale === 'en-US'
  const dataset = snapshot.datasets[0]
  const minuteCount = records.filter((record) => record.family !== 'Hermite 元因子' && record.frequencyIn === 'minute').length
  const hermiteCount = records.filter((record) => record.family === 'Hermite 元因子').length
  const fundamentalCount = records.filter((record) => record.frequencyIn === 'PIT quarterly reports').length
  const experimentalCount = records.filter((record) => record.status === 'experimental').length
  const familyCounts = [{ name: english ? 'Minute factors' : '分钟因子', value: minuteCount }, { name: 'Hermite', value: hermiteCount }, { name: english ? 'Fundamental entries' : '基本面研究入口', value: fundamentalCount }]
  return <main className="page">
    <section className="hero"><p className="eyebrow">{english ? 'RESEARCH NOTEBOOK / 01' : '研究笔记 / 01'}</p><h1>{english ? 'Turn market data into readable structure.' : '把市场数据，变成可读的结构。'}</h1><p className="lede">{english ? 'Browse market examples, factor definitions, and a separate fundamental PIT research vintage.' : '浏览市场示例、因子定义，以及独立的基本面 PIT 研究快照。'}</p><span className="badge">{snapshot.source === 'demo' ? 'DEMO MARKET SAMPLE' : 'MARKET SNAPSHOT'}</span></section>
    <ContextStrip items={[{ label: english ? 'Market data' : '市场数据', value: context.source }, { label: english ? 'Sample range' : '样本区间', value: context.snapshotRange }, { label: english ? 'Sample universe' : '样本股票池', value: context.universe }, { label: english ? 'Frequency' : '频率', value: english ? context.frequency : '日度示例观测' }]} />
    <p className="context-note">{snapshot.source === 'demo' ? (english ? 'Demonstration dataset. Dates include non-trading days; this is not a production market-data release.' : '演示数据集：日期包含非交易日，不代表正式行情数据发布。') : (english ? 'Published market snapshot; inspect source notes before interpreting coverage.' : '公开市场快照；解释覆盖范围前请核对来源说明。')}</p>
    <div className="metrics"><MetricCard label={snapshot.source === 'demo' ? english ? 'Sample dates' : '示例日期' : english ? 'Trading days' : '交易日'} value={dataset?.trading_days.toLocaleString() ?? '—'} note={`${dataset?.date_start ?? '—'} → ${dataset?.date_end ?? '—'}`} /><MetricCard label={english ? 'Market sample tickers' : '市场示例股票'} value={dataset?.tickers.toLocaleString() ?? '—'} note={english ? 'Not a full market universe' : '并非全市场股票池'} /><MetricCard label={english ? 'Catalog entries' : '目录条目'} value={records.length.toLocaleString()} note={`${minuteCount} minute · ${hermiteCount} Hermite · ${fundamentalCount} fundamental`} /><MetricCard label={english ? 'Experimental' : '实验性'} value={experimentalCount.toLocaleString()} note={english ? 'Predictive validation incomplete' : '预测性验证尚未完成'} /></div>
    <section className="panel provenance-panel"><p className="eyebrow">FUNDAMENTAL PIT / SEPARATE VINTAGE</p><h2>{english ? 'A distinct fundamental dataset' : '独立的基本面数据集'}</h2><p>{english ? `PIT observation range ${fundamental.coverage.date_start} → ${fundamental.coverage.date_end}; ${fundamental.coverage.tickers_count.toLocaleString()} tickers were processed. The charts show ${fundamental.coverage.representative_tickers.length} representative tickers. Availability basis: ${fundamental.validation.availability_basis}.` : `PIT 观察区间 ${fundamental.coverage.date_start} → ${fundamental.coverage.date_end}；处理了 ${fundamental.coverage.tickers_count.toLocaleString()} 只股票，图表仅展示 ${fundamental.coverage.representative_tickers.length} 只代表性股票。可用性口径：${fundamental.validation.availability_basis}。`}</p><a className="section-link" href={`${import.meta.env.BASE_URL}fundamentals`}>{english ? 'Explore fundamental evidence →' : '查看基本面证据 →'}</a></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">FACTOR ATLAS</p><div className="section-heading-row"><h2>{english ? 'Factor map' : '因子地图'}</h2><a className="section-link" href={`${import.meta.env.BASE_URL}factors`}>{english ? 'Browse all factors →' : '浏览全部因子 →'}</a></div></div><ResearchCharts kind="family" counts={familyCounts} english={english} /><div className="group-grid">{snapshot.factor_groups.map((group, index) => <a className="group-card" href={`${import.meta.env.BASE_URL}${index === 0 ? 'factors/realized_variance' : 'hermite'}`} key={group.name}><span className="group-index">0{index + 1}</span><div><h3>{group.label}</h3><p>{group.name}</p></div><strong>{index === 0 ? minuteCount : hermiteCount}</strong></a>)}<a className="group-card" href={`${import.meta.env.BASE_URL}fundamentals`}><span className="group-index">03</span><div><h3>{english ? 'Fundamental research' : '基本面研究'}</h3><p>{english ? 'Separate PIT vintage' : '独立 PIT 快照'}</p></div><strong>{fundamentalCount}</strong></a></div></section>
    <section className="section flow"><div className="section-heading"><p className="eyebrow">THE RESEARCH PATH</p><h2>{english ? 'From observations to evidence' : '从观测到研究证据'}</h2></div><div className="flow-row"><span>{english ? 'Prepared data' : '整理后的数据'}</span><i>→</i><span>{english ? 'Factor definitions' : '因子定义'}</span><i>→</i><span>{english ? 'Quality checks' : '质量检查'}</span><i>→</i><span>{english ? 'Published evidence' : '公开证据'}</span></div></section>
  </main>
}
